### ISSUE TITLE
doesn't work in v3.0.0 of swashbuckle

### ISSUE THREAD

**Issue by Allann** [scottbrady91/IdentityServer4-Swagger-Integration#1]
https://github.com/scottbrady91/IdentityServer4-Swagger-Integration/blob/f22a5883df9f616a5ff6e6a2141e3d063269ed56/src/Api.Swashbuckle/Startup.cs#L68

I altered this line of code, it's not as elegant but does the same job:
```
        public void Apply(Operation operation, OperationFilterContext context)
        {
            var found = false;
            if (context.ApiDescription.ActionDescriptor is Microsoft.AspNetCore.Mvc.Controllers.ControllerActionDescriptor controller)
            {
                found = controller.ControllerTypeInfo.GetCustomAttributes().OfType<AuthorizeAttribute>().Any();
            }
            if (!found)
            {
                if (!context.ApiDescription.TryGetMethodInfo(out var mi)) return;
                if (!mi.GetCustomAttributes().OfType<AuthorizeAttribute>().Any()) return;
            }

            operation.Responses.TryAdd("401", new Response { Description = "Unauthorized" });
            operation.Responses.TryAdd("403", new Response { Description = "Forbidden" });

            operation.Security = new List<IDictionary<string, IEnumerable<string>>>
            {
                new Dictionary<string, IEnumerable<string>>
                {
                    { "oauth2", new [] { "identityapi" } }
                }
            };
        }
```

This checks if the controller itself has the authorize attribute and if not checks the action.  Might be worth updating your blog post with this snippet.

**Comment by artiombell** [comment]
This fixes the issue: 

 var hasAuthorize = context.MethodInfo.DeclaringType.GetCustomAttributes(true)
                        .Union(context.MethodInfo.GetCustomAttributes(true)).Any();

**Comment by robnelder** [comment]
I may have misunderstood, but don't we need to check if the attribute is an Authorize attribute?

`var hasAuthorize = context.MethodInfo.DeclaringType.GetCustomAttributes(true).OfType<AuthorizeAttribute>().Union(context.MethodInfo.GetCustomAttributes(true).OfType<AuthorizeAttribute>()).Any();`
